
name: Publish package to GitHub Packages
on:
  release:
    types: [published]
env: 
  PERSONAL-TOKEN: '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'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@win-ther'
          
      - name: Configure npm for GitHub Packages
        run: |
          echo "@win-ther:registry=https://npm.pkg.github.com/" >> ~/.npmrc           
          echo "//npm.pkg.github.com/:_authToken=$PERSONAL-TOKEN" >> ~/.npmrc           
          echo "always-auth=true" >> ~/.npmrc
          
      - name: Verify .npmrc Configurations
        run: |
          if grep -q '@win-ther:registry=https://npm.pkg.github.com/' ~/.npmrc; then             
            echo "Registry configuration is correct."           
          else             
            echo "Error: Registry configuration is missing or incorrect."            
            exit 1           
          fi
          
          if grep -q '//npm.pkg.github.com/:_authToken' ~/.npmrc; then
            echo "Authentication token is set."
          else
            echo "Error: Authentication token is missing."
            exit 1
          fi
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: $PERSONAL-TOKEN
      - run: npm config ls -l
        env:
          NODE_AUTH_TOKEN: $PERSONAL-TOKEN
